name: Generate PDFs JSON

on:
  push:
    branches: [main]

permissions:
  contents: write # ✅ Habilita escritura al repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Find PDFs and generate JSON
        run: |
          repo_url="https://github.com/${{ github.repository }}/blob/main"
          echo "[" > pdfs.json
          first=true

          find . -type f -iname '*.pdf' | while read file; do
            # Obtener SHA del commit que agregó el archivo
            commit_sha=$(git log --diff-filter=A --format="%H" -- "$file")

            if [ -z "$commit_sha" ]; then
              echo "No commit found for $file, skipping."
              continue
            fi

            # Llamar a la API de GitHub para obtener la fecha del commit
            api_url="https://api.github.com/repos/${{ github.repository }}/commits/$commit_sha"
            date=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "$api_url" | jq -r '.commit.committer.date')

            # Si no se encontró fecha, usar fecha actual
            if [ -z "$date" ] || [ "$date" = "null" ]; then
              date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            fi

            clean_path="${file#./}"
            full_url="$repo_url/$clean_path"

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> pdfs.json
            fi

            echo "  { \"url\": \"$full_url\", \"date\": \"$date\" }" >> pdfs.json
          done

          echo "]" >> pdfs.json

      - name: Commit and push pdfs.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdfs.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate pdfs.json with PDF URLs and dates"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
