name: Generate PDFs JSON

on:
  push:
    branches: [main]

permissions:
  contents: write # ✅ Habilita escritura al repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Find PDFs and generate JSON
        run: |
          repo_url="https://github.com/${{ github.repository }}/blob/main"
          echo "[" > pdfs.json
          first=true
          find . -type f -iname '*.pdf' | while read file; do
            date=$(git log -1 --format="%ci" -- "$file")
            clean_path="${file#./}"
            full_url="$repo_url/$clean_path"
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> pdfs.json
            fi
            echo "  { \"path\": \"$clean_path\", \"url\": \"$full_url\", \"date\": \"$date\" }" >> pdfs.json
          done
          echo "]" >> pdfs.json

      - name: Commit and push pdfs.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdfs.json

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate pdfs.json with PDF paths and dates"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
